spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: http://localhost:8000/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"